### PR TITLE
added option to flatten output into single dir

### PR DESCRIPTION
**Pull request by tstephen**
I realise you've said this is no longer maintained so this is just an offer - feel free to ignore. 

In order to embed images in asciidoc I wanted to output all images in ${outputDirectory} where AsciiDoc expects them rather than ${outputDirectory/src/main/plantuml}

### CODE REVIEW

**Comment by jeluard** [comment]
I just received a notification about this request. I can transfer this repo to you, if it makes sense.

**Comment by jeluard** [comment]
Or maybe to you @arnaudroques ?

**Comment by arnaudroques** [comment]
Hi Julien, 

> Or maybe to you @arnaudroques ?

First, thanks again for your plugin.
Indeed, you can transfert this to me, it will help people to contribute on it.

If in some future you would like to take it back, just let me know!

**Comment by jeluard** [comment]
@arnaudroques Nice! You should have received a notification from GitHub then. Thanks for agreeing to help with it!

**Comment by arnaudroques** [comment]
@jeluard Sorry, the link seems to have expired. Could you send another notification? Thanks!

**Comment by tstephen** [comment]
Sorry @jeluard, I thought you meant @arnaudroques
<https://github.com/arnaudroques> in the first place. I've been looking at
how to get this onto maven central so if arnaudroques
<https://github.com/arnaudroques> doesn't want to I will take it on.

Thanks for a great tool

Tim Stephenson

**Pull request merged**
